### ISSUE TITLE
costumer_id is missing

### ISSUE THREAD

**Issue by jaysongyn** [Potelo/GuPayment#10]
Estou recebendo esse erro ao criar pagamento recorrente, não encontre onde passo esse parâmetro.

**Comment by gabrielpeixoto** [comment]
Pode me mostrar o trecho do código?

**Comment by jaysongyn** [comment]
$user->newSubscription('main', 'premium')->chargeOnSuccess()->create($data['creditCardToken']);

No ambiente de teste estava ok, quando atualizei api_key para fazer o teste em produção recebo o erro costumer_id is missing.

**Comment by jaysongyn** [comment]
@gabrielpeixoto vlw pela força. Enconttrei o problema, o user que estava testando na produção já estava com iugu_id e quando ele buscava esse user na live do iugu dava esse erro! vlw
