### ISSUE TITLE
subitems para assinatura - cobrança recorrente

### ISSUE THREAD

**Issue by leandrorocha** [Potelo/GuPayment#16]
@gabrielpeixoto como eu adiciono subitems na assinatura?

**Comment by gabrielpeixoto** [comment]
Olá, ainda não tem essa opção.

Se quiser pode fazer um pull request, que se tiver certinho eu aceito! =)

Tinham feito um em https://github.com/Potelo/GuPayment/pull/13, se quiser dar uma olhada.

Se você não tiver como fazer, vou deixar anotado, para quando tiver um tempinho fazer.
