### ISSUE TITLE
Implementar cobrança de fatura individual

### ISSUE THREAD

**Issue by willmkt** [Potelo/GuPayment#2]
No laravel cashier tem a opção de realizar cobrança individual(Single Charges)

Tem planos para fazer essa implementação?

**Comment by gabrielpeixoto** [comment]
Olá,

sim, tenho planos sim. já pretendo colocar em breve essa funcionalidade.

**Comment by willmkt** [comment]
Que bom, assim vai ficar mais completo..

O iugu tbm tem a opção de gerar segunda via de fatura, seria legal implementar tbm.

Valeu....

**Comment by paulocastellano** [comment]
+1

**Comment by dhsananias** [comment]
+1 Como está isso? foi implementado?

**Comment by gabrielpeixoto** [comment]
Olá, ainda não foi implementado não. =/
