### ISSUE TITLE
Atualizar itens de um plano?

### ISSUE THREAD

**Issue by jaysongyn** [Potelo/GuPayment#21]
Tem opção de adicionar itens, teria alguma forma de atualizar os itens de um plano que já possui assinatura ?

**Comment by gabrielpeixoto** [comment]
Olá @jaysongyn, ainda não tem essa opção de update nos itens da assinatura. Na verdade o único update que temos atualmente, é update do cartão de crédito do usuário.

Caso queira fazer um pull request para agilizar isso, seria legal! =)

**Comment by gabrielpeixoto** [comment]
Olá @jaysongyn consegui fazer o que você precisa. Esse pacote utiliza a biblioteca do Iugu por baixo, então dessa forma é possível criar novos items, alterar ou deletar:

    $usuario = Usuario::find(1);

    $subscription = $usuario->subscription('Main');

    $subscriptionIugu = $subscription->asIuguSubscription();

    // Adicionar novos itens
    $subscriptionIugu->subitems = [
        [
            'description' => 'Desconto recorrente',
            'price_cents' => -900,
            'quantity' => 1,
            'recurrent' => true,
        ],
        [
            'description' => 'Adicional não recorrente',
            'price_cents' => 250,
            'quantity' => 1,
            'recurrent' => false,
        ]
    ];

    $subscriptionIugu->save();

    // Editar o preço de um item existente
    $subscriptionIugu->subitems = [
        [
            'id' => 'ID DO SUBITEM',
            'price_cents' => 5000
        ]
    ];

    $subscriptionIugu->save();

    // Deletar um item existente
    $subscriptionIugu->subitems = [
        [
            'id' => 'ID DO SUBITEM',
            '_destroy' => true
        ]
    ];

    $subscriptionIugu->save();

Testa e me diz se conseguiu. :)

**Comment by jaysongyn** [comment]
> Olá @jaysongyn consegui fazer o que você precisa. Esse pacote utiliza a biblioteca do Iugu por baixo, então dessa forma é possível criar novos items, alterar ou deletar:
> 
> ```
> $usuario = Usuario::find(1);
> 
> $subscription = $usuario->subscription('Main');
> 
> $subscriptionIugu = $subscription->asIuguSubscription();
> 
> // Adicionar novos itens
> $subscriptionIugu->subitems = [
>     [
>         'description' => 'Desconto recorrente',
>         'price_cents' => -900,
>         'quantity' => 1,
>         'recurrent' => true,
>     ],
>     [
>         'description' => 'Adicional não recorrente',
>         'price_cents' => 250,
>         'quantity' => 1,
>         'recurrent' => false,
>     ]
> ];
> 
> $subscriptionIugu->save();
> 
> // Editar o preço de um item existente
> $subscriptionIugu->subitems = [
>     [
>         'id' => 'ID DO SUBITEM',
>         'price_cents' => 5000
>     ]
> ];
> 
> $subscriptionIugu->save();
> 
> // Deletar um item existente
> $subscriptionIugu->subitems = [
>     [
>         'id' => 'ID DO SUBITEM',
>         '_destroy' => true
>     ]
> ];
> 
> $subscriptionIugu->save();
> ```
> Testa e me diz se conseguiu. :)

Vlw funcionou :D
