### ISSUE TITLE
Array de opções na construção da assinatura (como funciona com clientes)

### ISSUE THREAD

**Issue by matheusb-comp** [Potelo/GuPayment#22]
Primeiramente, obrigado pela ótima biblioteca.

Os [dados adicionais](https://github.com/Potelo/GuPayment#dados-adicionais) passados à função `newSubscription()`, são enviados à API no parâmetro [`custom_variables`](https://github.com/Potelo/GuPayment/blob/master/src/SubscriptionBuilder.php#L290).
Já o array de `options` passado para a função [`create()`](https://github.com/Potelo/GuPayment/blob/master/src/SubscriptionBuilder.php#L166), é diferente, pois é expandido diretamente como [parâmetros](https://github.com/Potelo/GuPayment/blob/5869e36cb44d4e5e0dd341f42a2a1ef7f1df0a17/src/GuPaymentTrait.php#L142) enviados à API.

Assim, é possível customizar qualquer parâmetro na requisição para [criar cliente](https://dev.iugu.com/reference#criar-cliente) usando o array de opções, mas para customizar opções da [criação de assinatura](https://dev.iugu.com/reference#criar-assinatura) (como por exemplo o parâmetro `payable_with`) as [funções do builder](https://github.com/Potelo/GuPayment/blob/master/src/SubscriptionBuilder.php#L352) têm que ser utilizadas.

Existe uma maneira simples de customizar os parâmetros da requisição de criar assinatura para os casos onde não existe função equivalente no builder (ex: `ignore_due_email`)?

Como sugestão (posso enviar um pull request), seria interessante um parâmetro de opções na função `newSubscription()`, ou até mesmo substituir o array de dados adicionais por um array de opções (como acontece na criação de cliente) e permitir a adição das `custom_variables` por uma função específica do builder.

**Comment by gabrielpeixoto** [comment]
Olá @matheusb-comp, entendi o problema! Realmente dessa forma fica sem essa possibilidade.

Seria ótimo se pudesse enviar um pull request! 😄 

Acredito que seja melhor adicionar essa opção em vez de substituir o array de dados adicionais, pois aí conseguirei manter na versão 2.*.* (Quem utiliza, pode atualizar sem perder nenhuma funcionalidade). 

E fiz um teste aqui:
```php
$user->newSubscription('main', 'gold', ['adicional_assinatura' => 'boa assinatura'])
     ->create(NULL, [
	     'name' => $user->nome,
	     'adicional_cliente' => 'bom cliente'
	 ]);
```
e esse **adicional_cliente** nem é enviado para o iugu.

Então fico aguardando seu pull request, e vou ajustar a documentação nessa parte aí das opções do cliente, pois na documentação fica parecendo que são dados adicionais do cliente, porém na verdade são os **options**.
