### ISSUE TITLE
Próximo Vencimento

### ISSUE THREAD

**Issue by ricatom** [Potelo/GuPayment#24]
Olá, parabéns por este pacote

Gostaria de saber se tem como pegar o "Próximo Vencimento" da assinatura ?

Grato

**Comment by gabrielpeixoto** [comment]
Olá @ricatom !

Não temos isso implementado no pacote. Mas você pode fazer o seguinte:

No webhook de handleInvoiceCreated e no handleInvoiceStatusChanged, você pode atualizar essa informação no seu banco.

```php
$subscriptionIugu = $subscription->asIuguSubscription();
$next_invoice = new Carbon($subscriptionIugu->expires_at)
```
Testa e me diz se conseguiu

**Comment by ricatom** [comment]
@gabrielpeixoto deu certinho, muito obrigado
