### ISSUE TITLE
Gerar token de pagamento

### ISSUE THREAD

**Issue by ricatom** [Potelo/GuPayment#25]
Olá, tem como gerar o token de pagamento ?

**Comment by gabrielpeixoto** [comment]
Olá @ricatom. O ideal é fazer isso no lado do cliente (com javascript), e enviar o token por requisição.
Aqui tem como fazer isso: https://dev.iugu.com/docs/iugu-js.

Porém, se a sua aplicação não tiver javascript, pode ser feito via API, você pode fazer da seguinte forma (Utilizando diretamente a biblioteca Iugu PHP, que é instalada como dependência desse pacote):
```php
\Iugu::setApiKey(getenv('IUGU_APIKEY'));

$token = \Iugu_PaymentToken::create([
            "account_id" =>  getenv('IUGU_ID'),
            "method" => "credit_card",
            "data" => [
                "number" => "4111111111111111",
                "verification_value" => "123",
                "first_name" => "Joao",
                "last_name" => "Silva",
                "month" => "12",
                "year" => Carbon::now()->addYear()->year,
            ],
        ]);
```

Porém, sobre essa forma. Eles alertam o seguinte:
> Alerta de conformidade com PCI
> Esta chamada API deve ser utilizada apenas em aplicações sem compatibilidade com JavaScript como por exemplo aplicações móveis. Se você efetuar esta chamada por dentro de seus servidores estará sujeito a uma auditoria do PCI. Para aplicações WEB, utilize a geração do token de cartão pelo iugu.js

**Comment by ricatom** [comment]
OLá @gabrielpeixoto depois eu vi esse alerta deles, é que estou tendo dificuldades de adequar o exemplo deles para Vue.

Grato

**Comment by gabrielpeixoto** [comment]
Olha esse arquivo js do iugu modificado
[iugu.zip](https://github.com/Potelo/GuPayment/files/3447930/iugu.zip)

Você consegue importar ele assim:
```javascript
import Vue from 'vue'
import Iugu from '~/utils/iugu'

const iugu = Iugu()

if (!process.env.iuguId) {
  console.info(
    'O plugin do iugu não foi inicializado corretamente: accountId inválida.'
  )
}
// Set the account id on iugu instance
iugu.setAccountID(process.env.iuguId)

// Enable test mode when it is not in production
if (!process.env.isProduction) {
  console.info('Plugin do iugu inicializado no modo de testes.')
  iugu.setTestMode(true)
}

// Injects $iugu function in vue context
Vue.prototype.$iugu = iugu

```
