### ISSUE TITLE
get cards

### ISSUE THREAD

**Issue by rmeira** [Potelo/GuPayment#26]
Parabéns pelo projeto, estou tentando implementar o methodo $user->cards(), porém não está retornando os valor em json, retorna dessa forma...

[ {}, {}]

Sabe o que poderia ser?

**Comment by gabrielpeixoto** [comment]
Olá @rmeira 

O retorno desse método, é coleção da instância de Potelo\GuPayment\Card.

Olha aqui esse print, inspecionando o elemento:
![image](https://user-images.githubusercontent.com/3699061/62970834-c06ce300-bde6-11e9-89ac-be2cbb86359a.png)

Por exemplo, tenta chamar o atributo data em um item dessa coleção:
`$cards[0]->data
`

Obs. $cards = $user->cards();
