### ISSUE TITLE
Criar fatura

### ISSUE THREAD

**Issue by jammersonf** [Potelo/GuPayment#27]
Eu vi que na documentação dá pra pegar todas as faturas de um usuário, mas não vi a opção de criação de uma fatura. Tem no package ou vai ser disponibilizado?

**Comment by gabrielpeixoto** [comment]
Olá, na verdade esqueci de documentar esse método.

Aqui como um exemplo de como funciona:

`$invoice = $usuario->createInvoice($valorEmCentavos, Carbon::today(), $descricaoFatura, $options);`
