### ISSUE TITLE
Subscription

### ISSUE THREAD

**Issue by luizeduard0** [Potelo/GuPayment#3]
$user->subscription('main')

Nos meus testes o subscription está retornando null, dessa forma não consigo, por exemplo, cancelar uma assinatura...

**Comment by gabrielpeixoto** [comment]
Você pode mostrar o cenário em que ta chamando esse método?

Algumas perguntas:
- Esse usuário está com iugu_id no banco?
- A assinatura desse usuário está na tabela com o nome `main`?
- `$user->subscribed('main')` retorna true?
- No seu painel do Iugu, tem a assinatura lá?

**Comment by luizeduard0** [comment]
- Esse usuário está com iugu_id no banco? **Sim.**
- A assinatura desse usuário está na tabela com o nome main? O **nome não é main, mas consta a assinatura com nome equivalente.**
- $user->subscribed('main') retorna true? **Retornou false (Não sei porque. Nota: o usuário está em trial)**
- No seu painel do Iugu, tem a assinatura lá? **Sim, consta normal.**

O cenário é muito simples, simplesmente carreguei o user $user->find(..) e pedi para cancelar..
Mas ele dá erro no cancel porque o subscription() retorna null

**Comment by luizeduard0** [comment]
O nome do plano contém "-", pode interferir? Ex: unsm-plano-iniciante

**Comment by luizeduard0** [comment]
Subscription retorna sempre _null_ pra mim e subscribed sempre _false._

**Comment by gabrielpeixoto** [comment]
No lugar de 'main', você tem que utilizar o nome que utilizou para sua assinatura, o mesmo que ficou armazenado no banco de dados na tabela de assinatura.

$user->subscribed('**COLUNA NAME DA TABELA DE ASSINATURA**') retorna true?

**Comment by gabrielpeixoto** [comment]
Se puder me manda o resultado de `select * from SUA_TABELA_DE_ASSINATURAS`

**Comment by luizeduard0** [comment]
É o campo name? Achei que era o campo iugu_plan. Vou testar aqui com o name

**Comment by luizeduard0** [comment]
Agora foi beleza! Valeu, desculpe pela confusão... tinha entendi que era o iugu_plan.
