### ISSUE TITLE
Tratamento de webhook faz cancel funcionar como cancelNow

### ISSUE THREAD

**Issue by matheusb-comp** [Potelo/GuPayment#31]
Ao chamar a função [`cancel`](https://github.com/Potelo/GuPayment/blob/fa323a7cfcbe3c5baba87a39f412e2bf87205f1a/src/Subscription.php#L165) da assinatura, o valor do `expires_at` é usado para considerar se a assinatura vai ficar no _grace period_, enquanto a função `cancelNow` chama a função `markAsCanceled` e faz com que a assinatura não tenha _grace period_.

Porém, ao suspender a assinatura, o Iugu chama o _webhook_ `subscription.suspended`, que no [tratamento](https://github.com/Potelo/GuPayment/blob/fa323a7cfcbe3c5baba87a39f412e2bf87205f1a/src/Http/Controllers/WebhookController.php#L54) da biblioteca chama a função `markAsCanceled`.

Esse é o funcionamento esperado? Por que assim uma chamada para a função `cancel`, caso o _webhook_ esteja configurado, resulta no cancelamento da assinatura sem _grace period_.

**Comment by gabrielpeixoto** [comment]
Olá @matheusb-comp , realmente o ideal seria fazer de outra forma.

Vou verificar isso e modificar.

Caso queira, você pode criar o seu controller estendendo de WebhookController e sobrescrever esse método.

Acho que seria algo do tipo:
```php
if ($subscription->onTrial()) {
    $subscription->ends_at = $subscription->trial_ends_at;
} elseif (isset($subscriptionIugu->expires_at)) {
    $subscription->ends_at = Carbon::createFromFormat('Y-m-d', $subscriptionIugu->expires_at);
} else {
    $subscription->ends_at = Carbon::now();
}
```

Vou testar com calma e modifico. Caso queira fazer um PR será bem-vindo também!
