### ISSUE TITLE
Create plan

### ISSUE THREAD

**Issue by Iraecio** [Potelo/GuPayment#32]
Esse pacote não cria plano?

**Comment by gabrielpeixoto** [comment]
Olá,

Não tem essa funcionalidade no pacote, mas você consegue fazer chamando diretamente o método do Iugu php (Que já está instalado como dependência desse pacote).

Então basta fazer o seguinte:
```php
//\Iugu::setApiKey(env('IUGU_APIKEY'));
\Iugu::setApiKey(config('services.iugu.key'));

$plan = \Iugu_Plan::create([
    "name" => "Basic Plan",
    "identifier" => "basic_plan",
    "interval" => 1,
    "interval_type" => "months",
    "value_cents" => 2000
]);
```
Ref: https://dev.iugu.com/reference#criar-plano

Testa e me diz se conseguiu, que fecharei a issue.

**Comment by Iraecio** [comment]
Salve salve

Consegui sim @gabrielpeixoto 

Muito Obrigado
