### ISSUE TITLE
due_date em newSubscription

### ISSUE THREAD

**Issue by Overx** [Potelo/GuPayment#33]
Estou precisando definir os parametros de due_date e ensure_workday_due_date, e não estou encontrando como fazer isso. Alguém sabe como? Obrigado

**Comment by gabrielpeixoto** [comment]
Olá, tenta da seguinte forma:
```php
$user = User::find(1);

$qtdDiasAteVencimento = 10;

$user->newSubscription('main', 'gold')
            ->daysToExpire($qtdDiasAteVencimento )
            ->create();
```

Não encontrei o ensure_workday_due_date na api do Iugu, viu em que local sobre esse atributo?

**Comment by Overx** [comment]
> Olá, tenta da seguinte forma:
> 
> ```
> $user = User::find(1);
> 
> $qtdDiasAteVencimento = 10;
> 
> $user->newSubscription('main', 'gold')
>             ->daysToExpire($qtdDiasAteVencimento )
>             ->create();
> ```
> 
> Não encontrei o ensure_workday_due_date na api do Iugu, viu em que local sobre esse atributo?

Funcionando perfeitamente, obrigado Gabriel!
