### ISSUE TITLE
Remover opção Usar cartão de credito em cobranças futuras

### ISSUE THREAD

**Issue by Overx** [Potelo/GuPayment#34]
Boa tarde pessoal, estou com alguns clientes questionando sobre opção que salva dados do cartão, teria como remover essa opção?

https://uploaddeimagens.com.br/imagens/n1PU8zU

Agradeço.

**Comment by gabrielpeixoto** [comment]
Olá,

Nesse print que mandou, é a fatura diretamente no iugu. Aí só entrando em contato com eles para saber se tem como desativar essa opção.

**Comment by gabrielpeixoto** [comment]
Uma outra opção, é você criar a sua própria página de fatura, com as opções que desejar.
