### ISSUE TITLE
php artisan vendor:publish --all faz gerar Migration com data e hora zerado

### ISSUE THREAD

**Issue by felipemarques** [Potelo/GuPayment#36]
Ao rodar o comando: php artisan vendor:publish --all
Cria-se os seguintes arquivos:

0000_00_00_000000_add_subscription_columns_to_user_table.php
0000_00_00_000000_create_subscription_table.php

O problema nesse caso é quando roda o deploy no servidor.
O comando php artisan vendor:publish --all é pra funcionar no caso do dev colocar algum outro pacote novo na aplicacao, logo deveria rodar e publicar os arquivos em producao/homologacao.

Porem nao podemos rodar os migrations acima, antes de ter a tabela de users criada, pois gera erro.

Quando executar o comando de publish , deveria de alguma forma verificar se os arquivos de migrations ja foram criados ou se ja foram colocados na base de dados.

**Comment by gabrielpeixoto** [comment]
Olá @felipemarques, quando você diz "deveria de alguma forma verificar se os arquivos de migrations ja foram criados ou se ja foram colocados na base de dados.", você se refere a outros migrations, como o da tabela users, ou dos migrations do pacote?
