### ISSUE TITLE
A assinatura é dada como ativa mesmo se o usuário não efetuar o pagamento.

### ISSUE THREAD

**Issue by ddanborges** [Potelo/GuPayment#5]
Se você passar um token de um cartão que não aprove o pagamento no $user->newSubscription('main', 'assinatura')->create($token) a assinatura é dada como ativa. Da mesma forma com o pagamento com o boleto quando não se passa nenhum $token.

Pro cartão de crédito, teria a solução de implementar no newSubscription o pagamento em duas etapas do Iugu e só passar os dados para a tabela subscription na segunda etapa: http://support.iugu.com/hc/pt-br/articles/206914213-Fluxo-de-pagamento-em-duas-etapas

Pro boleto não tem um solução viável sem modificar um pouco a estrutura do Cashier pro Iugu. A diferença principal dos dois é que o Cashier é baseado no modelo do Stripe, onde o Stripe.js verifica se o pagamento é valido antes de criar a assinatura, diferente do Iugu.

Eu adaptei da seguinte forma:

Fluxo de pagamento de GuPayment:

1- Usuário clica no botão "Assinar"
2- É chamada a função createSubscription() onde ela cria uma nova assinatura e cancela a mesma colocando a data "agora" no campo ends_at.
3- Usuário é redirecionado para página da Invoice de sua assinatura com opção de pagar com boleto e cartão de crédito. (Os boletos só podem ser gerados depois da Invoice ser criada, e a Invoice só pode ser associada a uma assinatura se esta estiver sido criada previamente - segundo o Iugu.)
4- Usuário efetua pagamento, o hook invoice.status_changed é enviado. Ele verifica se o status da invoice mudou para "paid", caso sim insere o null na coluna ends_at.

```
public function createSubscription()
    {
        Auth::user()->newSubscription('main', 'mensal')->create();
        Auth::user()->subscription('main')->ends_at = Carbon::now();
        Auth::user()->subscription('main')->save();

        return view('signature');
    }

public function handleInvoiceStatusChanged(array $payload)
    {
        if($payload['data']['status'] == 'paid') {
            $subscription = Subscription::where('iugu_id', $payload['data']['subscription_id'])->first();

            $subscription->fill(['ends_at' => null])->save();
        }
        return new Response('Webhook Handled', 200);
    }

```

**Comment by gabrielpeixoto** [comment]
Coloquei uma opção de validar a assinatura apenas se o pagamento for aprovado (Caso o cliente cadastre uma forma de pagamento padrão). Caso queira controlar por boletos, pode utilizar o webhooks para verificar o não pagamento da fatura e cancelamento da assinatura.

Para utilizar a nova opção de apenas assinar se o pagamento for aprovado, pode utilizar da seguinte forma:

``` php
$user = User::find(1);

$user->newSubscription('main', 'gold')
->chargeOnSuccess()
->create($creditCardToken);
```
