### ISSUE TITLE
tentando criar uma assinatura teste

### ISSUE THREAD

**Issue by drolean** [Potelo/GuPayment#6]
> FatalThrowableError in GuPaymentTrait.php line 276:
> Call to undefined method Iugu_SearchResult::payment_methods()

segue código abaixo:

```
      $Token = Iugu_PaymentToken::create([
            "account_id" => env('ID_DA_CONTA'),
            "method" => "credit_card",
            "data" => [
                "number" => "4242424242424242",
                "verification_value" => "123",
                "first_name" => "Joao",
                "last_name" => "Silva",
                "month" => "12",
                "year" => "2013"
            ]
        ]);

        $Companie = \App\Companie::find(1);
        $Companie->newSubscription('consultor')->trialDays(21)->create($Token);
```

fazendo o mesmo teste via curl conforme documentação do iugu teria que me retornar um erro:

`{"errors":"Essa conta n\u00e3o est\u00e1 ativa para receber pagamentos pois n\u00e3o tem conta banc\u00e1ria cadastrada"}`

**Comment by gabrielpeixoto** [comment]
em `newSubscription('consultor')` deveria ter um segundo parâmetro, com o nome do plano para qual está assinando. E pelo que estou vendo na mensagem de erro, você está tentando utilizar a chave de produção e não de teste. checa essas coisas e me diz se o erro continua

**Comment by drolean** [comment]
ainda não consegui testar, mas não esta claro os parâmetros do newSubscription vi que tem 2 valores, mas não intendi o que são esses valores, o primeiro faz oque e o segundo???

**Comment by drolean** [comment]
Te fala que o erro ainda persiste, esta tudo ok. porem notei algo e necessário o email para fazer a subscription e no meu caso, o email do usuário esta atrelado a outra tabela:

`Companie->createAsIuguCustomer(object(Iugu_PaymentToken), array('email' => null)) in SubscriptionBuilder.php line 151`

coloquei na minha model para pegar o atributo email do usuário responsável agora passou

**Comment by gabrielpeixoto** [comment]
@drolean O newSubscription tem dois parâmetros, o primeiro é um nome para identificar sua assinatura na sua aplicação, esse nome não é utilizado no Iugu e sim na sua aplicação, se sua aplicação só tiver 1 tipo de assinatura, pode usar um nome padrão: 'main', 'principal', 'assinatura'. O segundo parâmetro é o nome do plano que você cadastrou no seu painel do Iugu.
