### ISSUE TITLE
Bug com atualização das informações da Assinatura

### ISSUE THREAD

**Issue by luizeduard0** [Potelo/GuPayment#8]
Estou com a seguinte situação: Tenho assinaturas mensais que possuem um período de testes (trial). Notei que se uma assinatura for alterada na Iugu (seja por mim ou pelo próprio sistema) o status não é refletido nas chamadas do package.

Se uma conta é cancelada, por exemplo, de forma "externa", ao chamar $user->subscription('main')->cancelled() ele retorna false, e se chamar $user->subscribed('main') ele retorna true, mesmo a assinatura estando cancelada e a API do Iugu retornando corretamente.

Qual a solução possível neste caso?

Obrigado!

**Comment by luizeduard0** [comment]
OBS: O webhook está configurado, mas mesmo alterando os dados no painel do Iugu ele não atualiza. Não está csrf protected.

**Comment by luizeduard0** [comment]
Depois de entrar em contato com o suporte do Iugu fui informado que eles não utilizam payload, as chamadas são enviadas com content-type application/x-www-form-urlencoded, tive que adaptar as funções para poder tratar os dados recebidos da forma adequada.

**Comment by gabrielpeixoto** [comment]
Olá,

poderia me mostrar algum exemplo para eu testar?

**Comment by luizeduard0** [comment]
@gabrielpeixoto Uma mudança simples resolve o problema, alterando WebhookController:

Ao invés de:
```php
$payload = json_decode($request->getContent(), true);
```

basta utilizar:
```php
$payload = $request->all();
```

**Comment by luizeduard0** [comment]
De qualquer forma no meu caso, tive que adicionar outros handlers para poder lidar com todos os webhooks que precisei.

**Comment by gabrielpeixoto** [comment]
Já tinha feito isso anteriormente em #9a53ae2

Dá um update na versão que vai corrigir
