### ISSUE TITLE
Funcionalidades para pagamento de times

### ISSUE THREAD

**Issue by paulocastellano** [Potelo/GuPayment#9]
Olá,

Percebi que não está funcionando para times o pacote pelo seguinte fato.

Tenho as tabelas "companias, usuários e assinaturas".

Coloquei o trait na companias, para ela ter o iugu_id, porém não consigo usar porque ele não acha o customer id.

Verifiquei o código do pacote e o problema está por que em vários lugares você chama queries por "user_id" e no meu caso seria "compania_id" vamos supor.

Não tem como deixar isso dinamico?

Abraços

**Comment by gabrielpeixoto** [comment]
Olá @paulocastellano, vou dar uma olhada e ver como posso colocar

**Comment by gabrielpeixoto** [comment]
@paulocastellano Enviei algumas alterações em 2c56e8cabf30951a167f8fce63e8e1db8ed5aa43

Atualize o pacote para a versão 1.2.1, e adicione **model_foreign_key** em config/services.php:
```
'iugu' => [
    'model'  => App\User::class,
    'key' => env('IUGU_APIKEY'),
    'signature_table' => env('GUPAYMENT_SIGNATURE_TABLE'),
    'model_foreign_key' => env('IUGU_MODEL_FOREIGN_KEY')
]
```
Aí basta colocar o nome da sua coluna no .env
`IUGU_MODEL_FOREIGN_KEY=compania_id`
